spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    url: jdbc:mysql://localhost:3306/pilottest?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    mapper-locations: classpath:com.pilot.test.mapper/*.xml

logging:
  config: classpath:log4j2.xml

## Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  typeAliasesPackage: com.pilot.test.*.model
  global-config.id-type: 0
  global-config.field-strategy: 1
  global-config.db-column-underline: true
  global-config.logic-delete-value: 1
  global-config.logic-not-delete-value: 0
  configuration.map-underscore-to-camel-case: true
  configuration.cache-enabled: false

api:
  version: 1

jwtp.store-type: 1
jwtp.max-token: 3
jwtp.path: /v1/**
jwtp.exclude-path: /v1/user/login
